### ISSUE TITLE
Unable to connect device

### ISSUE THREAD

**Issue by xcD6** [ano0002/Leap-Motion-Python-3.8#3]
Hi, I installed the latest version of the driver provided on the official website and connected Leap Motion to my computer, but I couldn't connect to the device when running the .py file using Python 3.8. What is the reason for this?
![1V](https://github.com/ano0002/Leap-Motion-Python-3.8/assets/88928302/c7afec4f-11ba-4d08-98f1-99bf04800e4d)

**Comment by ano0002** [comment]
This script doesn't work with the latest sdk. It works with the sdk v3.2.
You can find it [here](https://leap2.ultraleap.com/gemini-downloads/) under `Technical Details` then `Legacy Downloads`.
If you want to use a newer version of the sdk I know you can find python build for up to sdk v4.1 [here](https://github.com/seanschneeweiss/RoSeMotion/tree/master/app/resources/LeapSDK). I just saw they have also v5.3 but I haven't used it.

**Comment by xcD6** [comment]
Thanks. I have successfully connected to leap motion.



发自我的iPhone


------------------ Original ------------------
From: Anatole Sot ***@***.***&gt;
Date: Mon,Mar 4,2024 1:15 AM
To: ano0002/Leap-Motion-Python-3.8 ***@***.***&gt;
Cc: xcD6 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ano0002/Leap-Motion-Python-3.8] Unable to connect device (Issue#3)





 
This script doesn't work with the latest sdk. It works with the sdk v3.2.
 You can find it (here)[https://leap2.ultraleap.com/gemini-downloads/] under Technical Details then Legacy Downloads.
 If you want to use a newer version of the sdk I know you can find python build for up to sdk v4.1 (here)[https://github.com/seanschneeweiss/RoSeMotion/tree/master/app/resources/LeapSDK]. I just saw they have also v5.3 but I haven't used it.
