### ISSUE TITLE
How did you make this python sdk?

### ISSUE THREAD

**Issue by sakarisx** [ano0002/Leap-Motion-Python-3.8#5]
Hi there and thank your work, I see that you recompiled leap motion sdk v3.2. And there is a new version sdk released(v5.17.1). What I need to do if I want to use the new version sdk in my python project?

**Comment by ano0002** [comment]
I followed this guide : https://support.ultraleap.com/hc/en-us/articles/360004362237-Generating-a-Python-3-3-0-Wrapper-with-SWIG-2-0-9
